networks:
  my-local-network:

volumes:
  local-postgres:

services:
  web-backend:
    build: .
    platform: linux/amd64
    networks:
      - my-local-network
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@my-postgres:5432"
      DATABASE_NAME: "mydb"
    ports:
      - "8000:8000"
    depends_on:
      my-postgres:
        condition: service_healthy

  my-postgres:
    image: postgres:15
    platform: linux/amd64
    networks:
      - my-local-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - local-postgres:/var/lib/postgresql/data
      # - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
